scssphp:
    enabled: true
    autoUpdate: true
    # site specific
    assets:
        "css/base.css":
            src: "assets/scss/base.scss"
            sourceMap: false
            # Array of import paths, relative to Symfony's project directory.
            importPaths:
                - "assets/scss"                        # main directory
