twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        siteName: '%app.site.name%'
        siteTagline: ''
        siteEmail: '%app.site.email%'
        sitePublisher: '%app.site.publisher%'
        # the following two are used by TeiEditionBundle for for dfg-viewer
        sitePublisherUrl: '%app.site.publisher_url%'
        sitePublisherLogo: '%app.site.publisher_logo%'
        slugify: "@cocur_slugify"
        public_dir: '%app.public_dir%'
        webDir: '%app.public_dir%'  # global expected by TeiEditionBundle
        site_matomo_id: '%app.site.matomo.id%'

when@test:
    twig:
        strict_variables: true
